name: 自动


on:

  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - scripts/**
      - .github/**
jobs:
  build:
    name: 运行脚本
    runs-on: ubuntu-latest
    steps:
      #- name: 检出代码
      #  uses: actions/checkout@v3
      - name: 设置 node 版本
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      #    cache: yarn
      #- name: 配置环境
      #  run: |
      #    yarn install
      #- name: 运行脚本
      #  run: |
      #    node scripts/main.js
      #- name: 查看运行情况
      #  run: |
      #    tree
      
      - name: 启动构建
        run: |
          npx create-docusaurus@latest website classic
          cd website
          yarn install
          yarn build
      
      - name: 查看运行情况
        run: |
          tree
